#!/sbin/openrc-run
# Copyright 1999-2017 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2

description="Deamon for controlling Teres' caps lock and num lock leds"

DEVICE=${DEVICE:-"/dev/input/by-path/platform-1c1b000.ehci1-controller-usb-0:1.4:1.0-event-kbd"}

command="/usr/bin/teres1-ledctrl"
command_args="${DEVICE}"
pidfile="/run/teres1-ledctrl.pid"
start_stop_daemon_args="--background --make-pidfile
    --stdout /dev/null --stderr /dev/null"
